# Generated by Django 3.0.1 on 2019-12-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_content_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_detail',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
